name: greenfield_seller
description: greenfieldSeller

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.15
  http: ^1.1.0
  connectivity_plus: ^4.0.1
  provider: ^6.0.2
  flutter_svg: ^2.0.6
  flutter_widget_from_html: ^0.10.1
  firebase_core: ^2.2.0
  flutter_localization: ^0.1.11
  shimmer: ^3.0.0
  url_launcher: ^6.1.12
  firebase_messaging: ^14.6.5
  fl_chart: ^0.63.0
  html_editor_enhanced: ^2.5.1
  file_picker: ^5.2.5
  path_provider: ^2.0.11
  geolocator: ^9.0.1 #for user location
  flutter_google_places: ^0.3.0
  google_maps_flutter: ^2.2.0  #for map
  geocoding: ^2.0.4
  intl: ^0.18.1
  awesome_notifications: ^0.8.2
  permission_handler: ^10.4.3


dependency_overrides:
  intl: ^0.17.0
  http: ^0.13.4
  modal_bottom_sheet:
    git:
      url: https://github.com/danReynolds/modal_bottom_sheet.git
      path: modal_bottom_sheet
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/svg/
    - assets/images/
    - assets/mapTheme/

font:
  - family: Lato
    fonts:
      - assets/fonts/Lato-Regular.ttf